#!/usr/bin/env php
<?php

require __DIR__ . '/../framework/vendor/autoload.php';
require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';

$kernel = $app->make(Elephant\Contracts\Mail\Kernel::class);

$kernel->handle();
