#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';

if ($argv[1] == 'start') {
    $kernel = $app->make(Elephant\Contracts\EventLoop\Kernel::class);

    $kernel->bootstrap();

    $kernel->handle();

    $kernel->terminate();
} else {
    // @todo Implement standard console access to allow for 
    //       scaffolding and the like.
}
